github registry login
smu-chile/aws-ecr-policy-action pull request #3
Opened 2022-08-17 21:12 UTC by fjleivad

## What problem is this solving?
    adding description here

## Types of changes

- Added function to login to ghcr.io

## Checklist

- [X] New feature (a non-breaking change which adds functionality)

2022-08-17 21:19 UTC, jveraduran requested changes
CHANGE
```
function main() -->
sanitize "${INPUT_GH_REGISTRY_TOKEN}" "gh_registry_token"
sanitize "${INPUT_GH_REGISTRY_USER}" "gh_registry_user"
```

Ademas en function gh_login()--->
export GH_REGISTRY_USER=$GH_REGISTRY_USER

2022-08-17 21:40 UTC, fjleivad reviewed
Se realizaron las correcciones detalladas

2022-08-17 21:46 UTC, jveraduran approved these changes
LGTM

2022-08-18 13:05 UTC, amaclemandry approved these changes
Aprobado

2022-08-18 13:06 UTC, merged